#!/bin/sh
echo "*****************************************"
echo "*      Internet SpeedTest Installed     *"
echo "*              By Madhouse              *"
echo "*****************************************"
sleep 2
echo $LINE
echo "*****************************************"
echo "*            Restart Enigma2            *"
echo "*****************************************"
sleep 2
killall -9 enigma2
exit 0
