#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/InternetSpeedTest > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Converter/SP* > /dev/null 2>&1
echo "*****************************************"
echo "*    Restart GUI to finish uninstall!   *"
echo "*****************************************"
sleep 6
exit 0
