#!/bin/sh
echo "*****************************************"
echo "*      Internet SpeedTest Installed     *"
echo "*****************************************"
sleep 2
echo $LINE
echo "*****************************************"
echo "*            Restart Enigma2            *"
echo "*****************************************"
sleep 2
killall -9 enigma2
rm -r /CONTROL
rm -r /var/volatile/tmp/*.ipk
exit 0
